name: flutter_batch16
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #device_preview: // device preview er jnne kn diceice valo hobe r reoponsib hochje ki na dekhar jnne
  device_preview:
  #flutter svg // svg picture support er jnne
  flutter_svg:
  #pinput  // input er decoradion er jnne
  pinput: ^6.0.2
  #http // api call er jnne
  http: ^1.1.0
  #Logger // debug chack korar jnne
  logger:
  #shared_preferences: ^2.5.5 //token save korar jnne
  shared_preferences:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
